### ISSUE TITLE
TRACY_ON_DEMAND profiling and TracyPlotConfig

### ISSUE THREAD

**Issue by benny-edlund** [wolfpld/tracy#632]
Seems in my tests like we get stuck on a mutex when I do TracyPlotConfig duration construction of a class after main() when having TRACY_ON_DEMAND enabled.

```
"Thread 1 (Thread 0x7f4b022d9000 (LWP 22770)):",
"#0  0x00007f4b14675bb9 in poll () from /lib/x86_64-linux-gnu/libc.so.6",
"#1  0x0000000000c9734e in xxxxxx () at xxxx",
"#2  <signal handler called>",
"#3  0x00007f4b149631fb in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0",
"#4  0x00007f4b1495c025 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0",
"#5  0x0000000000c76b41 in __gthread_mutex_lock () at /vol/weta/linux64/gcc/ubuntu-18.04/gcc-6.4.0/include/c++/6/x86_64-linux-gnu/bits/gthr-default.h:748",
"#6  std::mutex::lock () at /vol/weta/linux64/gcc/ubuntu-18.04/gcc-6.4.0/include/c++/6/bits/std_mutex.h:103",
"#7  tracy::Profiler::DeferItem () at /vol/apps/tracy/0.9.1/gcc-6.4.0/include/client/TracyProfiler.hpp:687",
"#8  tracy::Profiler::ConfigurePlot () at /vol/apps/tracy/0.9.1/gcc-6.4.0/include/client/TracyProfiler.hpp:357",
"#9 ....
```

I did not see any special cases mentioned in the documentation.

**Comment by benny-edlund** [comment]
User error

Client was not compiled with the same flags
