### ISSUE TITLE
Tracy v0.9.1 ubuntu 22.04  launch Aborted (core dumped)

### ISSUE THREAD

**Issue by Wuqiqi123** [wolfpld/tracy#676]
OS: ubuntu 22.04

Tracy version 0.9.1. 
but 0.9 is fine.

```
./Tracy-release 
Cannot establish wayland display connection!
terminate called without an active exception
Aborted (core dumped)

```

gdb call stack
```
gdb Tracy-debug
Starting program: /home/wqq/tracy/profiler/build/unix/Tracy-debug 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6d53640 (LWP 25829)]
[New Thread 0x7ffff6552640 (LWP 25830)]
[New Thread 0x7ffff5d51640 (LWP 25831)]
Cannot establish wayland display connection!
terminate called without an active exception
[Thread 0x7ffff6d53640 (LWP 25829) exited]
[Thread 0x7ffff5d51640 (LWP 25831) exited]

Thread 1 "Tracy-debug" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737343852544) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, 
    threadid=140737343852544) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, 
    threadid=140737343852544) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737343852544, 
    signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7042476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007ffff70287f3 in __GI_abort ()
    at ./stdlib/abort.c:79
#5  0x00007ffff74a2b9e in ?? ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff74ae20c in ?? ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff74ae277 in std::terminate() ()
   from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x0000555555b6de75 in std::thread::~thread (
    this=0x555556e21228 <updateThread>, 
    __in_chrg=<optimized out>)
    at /usr/include/c++/11/bits/std_thread.h:152
#9  0x00007ffff7045495 in __run_exit_handlers (status=1, 
    listp=0x7ffff7219838 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true, 
    run_dtors=run_dtors@entry=true) at ./stdlib/exit.c:113
#10 0x00007ffff7045610 in __GI_exit (
    status=<optimized out>) at ./stdlib/exit.c:143
#11 0x000055555604735a in Backend::Backend(char const*, std::function<void ()>, RunQueue*) (this=0x7fffffffd100, 
    title=0x555556e211a0 <title> "Tracy Profiler 0.9.1", 
    redraw=..., 
    mainThreadTasks=0x555556e21380 <mainThreadTasks>)
    at ../../src/BackendWayland.cpp:642
#12 0x0000555556035549 in main (argc=1, 
    argv=0x7fffffffd648) at ../../src/main.cpp:225

```

**Comment by Wuqiqi123** [comment]
> Read release notes.

Yes. Thanks.

**Comment by Vollkornaffe** [comment]
```
cd profiler
cmake -DLEGACY=1 ..
make -j
```
Worked for me
