### ISSUE TITLE
Tracy Profiler Crashes with Context Switch feature

### ISSUE THREAD

**Issue by satyajitidea** [wolfpld/tracy#856]
I am facing one crashing issue with Profiler when Context switch feature is use:

Here is the crashing call stack:
```
$./tracy-profiler
tracy-profiler: /home/satyajit/projects/tracy/server/TracyWorker.cpp:6673: void tracy::Worker::ProcessContextSwitch(const tracy::QueueContextSwitch&): Assertion `item.End() == -1' failed.
Aborted (core dumped)
```
Normally, tracy profiler works with context switch information, but occasionally it crashes with above call stack. Any help would be appreciated.

**Comment by wolfpld** [comment]
You can probably build with asserts disabled and it will work. The worst that can happen is that some context switches will have incorrect data. But at that point, the incoming data is invalid anyway (the asserts protect against that), so the only solution would be to ignore the offending events. FWIW I can reproduce this on my end.

**Comment by satyajitidea** [comment]
Thank you so much!!
After disabling assert,i can see tracy profiler is working as expected.

**Comment by erieaton-amd** [comment]
I've run into this same issue elsewhere, disabling assertions does allow me to get a trace. Do you know how the data becomes incorrect? We'd rather have the valid context switch information.

**Comment by YaLTeR** [comment]
Been hitting what seems to be a related assertion on a debug build of tracy-profiler. In case it's helpful:

```
tracy-profiler: /var/home/yalter/source/cpp/tracy/server/TracyWorker.cpp:6898: void tracy::Worker::ProcessContextSwitch(const tracy::QueueContextSwitch&): Assertion `data.empty() || (uint64_t)data.back().End() <= (uint64_t)time' failed.

Thread 132 "Tracy Worker" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffaefed6c0 (LWP 280137)]
0x00007ffff71eb3cc in __pthread_kill_implementation () from /lib64/libc.so.6
Missing rpms, try: dnf --enablerepo='*debug*' install libglvnd-egl-debuginfo-1.7.0-8.fc43.x86_64 libwayland-egl-debuginfo-1.24.0-1.fc43.x86_64 libwayland-client-debuginfo-1.24.0-1.fc43.x86_64 libwayland-cursor-debuginfo-1.24.0-1.fc43.x86_64 libxkbcommon-debuginfo-1.11.0-1.fc43.x86_64 freetype-debuginfo-2.13.3-3.fc43.x86_64 libidn2-debuginfo-2.3.8-2.fc43.x86_64 openssl-libs-debuginfo-3.5.4-1.fc43.x86_64 zlib-ng-compat-debuginfo-2.3.2-2.fc43.x86_64 libbrotli-debuginfo-1.2.0-1.fc43.x86_64 libnghttp2-debuginfo-1.66.0-2.fc43.x86_64 dbus-libs-debuginfo-1.16.0-4.fc43.x86_64 libstdc++-debuginfo-15.2.1-5.fc43.x86_64 glibc-debuginfo-2.42-5.fc43.x86_64 libgcc-debuginfo-15.2.1-5.fc43.x86_64 libglvnd-debuginfo-1.7.0-8.fc43.x86_64 libffi-debuginfo-3.5.2-1.fc43.x86_64 bzip2-libs-debuginfo-1.0.8-21.fc43.x86_64 libpng-debuginfo-1.6.53-1.fc43.x86_64 harfbuzz-debuginfo-11.5.1-1.fc43.x86_64 libunistring-debuginfo-1.1-10.fc43.x86_64 systemd-libs-debuginfo-258.3-2.fc43.x86_64 glib2-debuginfo-2.86.3-1.fc43.x86_64 graphite2-debuginfo-1.3.14-19.fc43.x86_64 libcap-debuginfo-2.76-3.fc43.x86_64 pcre2-debuginfo-10.47-1.fc43.x86_64 mesa-libEGL-debuginfo-25.2.7-3.fc43.x86_64 mesa-va-drivers-freeworld-debuginfo-25.2.7-2.fc43.x86_64 mesa-libgbm-debuginfo-25.2.7-3.fc43.x86_64 expat-debuginfo-2.7.3-1.fc43.x86_64 libX11-xcb-debuginfo-1.8.12-1.fc43.x86_64 libxcb-debuginfo-1.17.0-6.fc43.x86_64 libdrm-debuginfo-2.4.128-3.fc43.x86_64 llvm-libs-debuginfo-21.1.7-1.fc43.x86_64 libzstd-debuginfo-1.5.7-2.fc43.x86_64 spirv-tools-libs-debuginfo-2025.4-1.fc43.x86_64 lm_sensors-libs-debuginfo-3.6.0-23.fc43.x86_64 libxshmfence-debuginfo-1.3.2-7.fc43.x86_64 elfutils-libelf-debuginfo-0.194-1.fc43.x86_64 libXau-debuginfo-1.0.12-3.fc43.x86_64 libedit-debuginfo-3.1-57.20251016cvs.fc43.x86_64 libxml2-debuginfo-2.12.10-5.fc43.x86_64 libpciaccess-debuginfo-0.16-16.fc43.x86_64 ncurses-libs-debuginfo-6.5-7.20250614.fc43.x86_64 xz-libs-debuginfo-5.8.1-4.fc43.x86_64 libglvnd-opengl-debuginfo-1.7.0-8.fc43.x86_64
(gdb) bt
#0  0x00007ffff71eb3cc in __pthread_kill_implementation () from /lib64/libc.so.6
#1  0x00007ffff719115e in raise () from /lib64/libc.so.6
#2  0x00007ffff71786d0 in abort () from /lib64/libc.so.6
#3  0x00007ffff7178639 in __assert_fail_base.cold () from /lib64/libc.so.6
#4  0x00000000009c8ca9 in tracy::Worker::ProcessContextSwitch (this=0x2a6b6f8, ev=...)
    at /var/home/yalter/source/cpp/tracy/server/TracyWorker.cpp:6898
#5  tracy::Worker::Process (this=0x2a6b6f8, ev=...) at /var/home/yalter/source/cpp/tracy/server/TracyWorker.cpp:4730
#6  tracy::Worker::DispatchProcess (this=0x2a6b6f8, ev=..., ptr=<optimized out>)
    at /var/home/yalter/source/cpp/tracy/server/TracyWorker.cpp:3348
#7  tracy::Worker::Exec (this=0x2a6b6f8) at /var/home/yalter/source/cpp/tracy/server/TracyWorker.cpp:2874
#8  0x000000000093b6b1 in operator() (__closure=0x35b5968)
    at /var/home/yalter/source/cpp/tracy/server/TracyWorker.cpp:290
#9  0x0000000000a18e68 in std::__invoke_impl<void, tracy::Worker::Worker(char const*, uint16_t, int64_t)::<lambda()> >(std::__invoke_other, struct {...} &&) (__f=...) at /usr/include/c++/15/bits/invoke.h:63
#10 0x0000000000a18c06 in std::__invoke<tracy::Worker::Worker(char const*, uint16_t, int64_t)::<lambda()> >(struct {...} &&) (__fn=...) at /usr/include/c++/15/bits/invoke.h:98
#11 0x0000000000a18954 in std::thread::_Invoker<std::tuple<tracy::Worker::Worker(char const*, uint16_t, int64_t)::<lambda()> > >::_M_invoke<0>(std::_Index_tuple<0>) (this=0x35b5968) at /usr/include/c++/15/bits/std_thread.h:303
#12 0x0000000000a1879c in std::thread::_Invoker<std::tuple<tracy::Worker::Worker(char const*, uint16_t, int64_t)::<lambda()> > >::operator()(void) (this=0x35b5968) at /usr/include/c++/15/bits/std_thread.h:310
#13 0x0000000000a18684 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tracy::Worker::Worker(char const*, uint16_t, int64_t)::<lambda()> > > >::_M_run(void) (this=0x35b5960) at /usr/include/c++/15/bits/std_thread.h:255
#14 0x00007ffff74d93e4 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#15 0x00007ffff71e9464 in start_thread () from /lib64/libc.so.6
#16 0x00007ffff726c5ac in __clone3 () from /lib64/libc.so.6
(gdb) up
#1  0x00007ffff719115e in raise () from /lib64/libc.so.6
(gdb)
#2  0x00007ffff71786d0 in abort () from /lib64/libc.so.6
(gdb)
#3  0x00007ffff7178639 in __assert_fail_base.cold () from /lib64/libc.so.6
(gdb)
#4  0x00000000009c8ca9 in tracy::Worker::ProcessContextSwitch (this=0x2a6b6f8, ev=...) at /var/home/yalter/source/cpp/tracy/server/TracyWorker.cpp:6898
6898	            assert( data.empty() || (uint64_t)data.back().End() <= (uint64_t)time );
(gdb) p data
$1 = (tracy::Vector<tracy::ContextSwitchData> &) @0x7fffc80c860d: {m_ptr = {m_ptr = "\240Ž\003\000"}, m_size = 27112, m_capacity = 15 '\017', m_magic = 0 '\000'}
```
